In [ ]:
import numpy as np

In [6]:

A= np.array([[1,-2,3],[2,1,-1],[-1,1,2]])

b= np.array([[1],[3],[7]]) 


x= np.linalg.solve(A, b) 

 
print( 

f''' 

n= {3},  

A= {A} 

b= {b} 

x= {x} 

''') 

 

n= 3,  

A= [[ 1 -2  3]
 [ 2  1 -1]
 [-1  1  2]] 

b= [[1]
 [3]
 [7]] 

x= [[0.94444444]
 [3.38888889]
 [2.27777778]] 




In [7]:
A= np.array([[1,-2,3,1,-2],[2,1,-1,-1,+1],[-1,1,2,2,-3],[2,1,-1,-1,2],[1,3,-2,2,-2]])

b= np.array([[-1],[3],[7],[5],[-4]]) 


x= np.linalg.solve(A, b) 

 
print( 

f''' 

n= {3},  

A= {A} 

b= {b} 

x= {x} 

''') 

 

n= 3,  

A= [[ 1 -2  3  1 -2]
 [ 2  1 -1 -1  1]
 [-1  1  2  2 -3]
 [ 2  1 -1 -1  2]
 [ 1  3 -2  2 -2]] 

b= [[-1]
 [ 3]
 [ 7]
 [ 5]
 [-4]] 

x= [[-0.625]
 [ 5.625]
 [ 5.75 ]
 [-2.375]
 [ 2.   ]] 




In [8]:

np.random.seed(0) 

n = 10

A= np.random.randint(-5,5,size=(n,n)) 


np.random.seed(1) 


b= np.random.randint(-5,5,size=(n,1)) 

 

x= np.linalg.solve(A, b) 

 

print( 

f''' 

n= {n},  

A= {A} 

b= {b} 

x= {x} 

''') 

 

n= 10,  

A= [[ 0 -5 -2 -2  2  4 -2  0 -3 -1]
 [ 2  1  3  3 -4  1  2  2  3 -4]
 [ 0  4  3  4 -1 -2 -5 -2  0 -5]
 [-3 -2  3 -4 -2 -2 -2  2 -5 -4]
 [ 4  4 -5 -1  2 -2 -3  2 -3 -5]
 [-5 -1  0  0  1  3 -1 -4 -1  4]
 [ 3 -4 -4  2  4  4 -2  1  2 -3]
 [-5 -2  0  4 -1 -1  1 -1 -1 -2]
 [-1 -1  3 -1 -2  2  0  0 -5 -4]
 [ 0  4 -2 -5  0 -5 -4 -3 -1 -3]] 

b= [[ 0]
 [ 3]
 [ 4]
 [ 0]
 [-5]
 [-5]
 [-4]
 [ 2]
 [ 1]
 [ 4]] 

x= [[ 2.41026587]
 [-2.33689728]
 [-0.30247412]
 [ 0.90538128]
 [-2.84414544]
 [-1.88566993]
 [-0.59590749]
 [-2.26735821]
 [-0.75324469]
 [ 0.69925056]] 


