In [1]:
import numpy as np


In [4]:
#%% 

# when n is large, it is very slow!! 

n= np.random.randint(2,5) 

A= np.random.randint(-5,5,size=(n,n)) 

print(f'A= \n{A}') 

 

def ryDet(A): 

     

    n= A.shape[0] 

    if n>1: 

        i= 0 

        Bi=  np.delete(A, i, axis=0) 

        #print(f'\ni= {i}, Bi= \n{Bi}') 

         

        det= 0 

        for j in range(n): 

             

            Bij= np.delete(Bi,j, axis=1) 

            print(f'\ni,j= {i}{j}, Bij= \n{Bij}') 

             

            Dij= ryDet(Bij) #np.linalg.det(Bij) 

            print(f'.... Dij= {Dij}') 

             

            Cij= A[i,j]*Dij*(-1)**(i+j) 

            det += Cij 

        #print(f'det= {det}') 

        return det 

     

    elif A.shape[0]==1: 

        det= A[0,0] 

        return det 

    else: 

        return None 

 

det= ryDet(A) 

print(f'\ndet= {det}') 



A= 
[[ 4 -4 -4 -1]
 [-5  2  2  2]
 [ 2  3  2 -2]
 [-2 -2  4  2]]

i,j= 00, Bij= 
[[ 2  2  2]
 [ 3  2 -2]
 [-2  4  2]]

i,j= 00, Bij= 
[[ 2 -2]
 [ 4  2]]

i,j= 00, Bij= 
[[2]]
.... Dij= 2

i,j= 01, Bij= 
[[4]]
.... Dij= 4
.... Dij= 12

i,j= 01, Bij= 
[[ 3 -2]
 [-2  2]]

i,j= 00, Bij= 
[[2]]
.... Dij= 2

i,j= 01, Bij= 
[[-2]]
.... Dij= -2
.... Dij= 2

i,j= 02, Bij= 
[[ 3  2]
 [-2  4]]

i,j= 00, Bij= 
[[4]]
.... Dij= 4

i,j= 01, Bij= 
[[-2]]
.... Dij= -2
.... Dij= 16
.... Dij= 52

i,j= 01, Bij= 
[[-5  2  2]
 [ 2  2 -2]
 [-2  4  2]]

i,j= 00, Bij= 
[[ 2 -2]
 [ 4  2]]

i,j= 00, Bij= 
[[2]]
.... Dij= 2

i,j= 01, Bij= 
[[4]]
.... Dij= 4
.... Dij= 12

i,j= 01, Bij= 
[[ 2 -2]
 [-2  2]]

i,j= 00, Bij= 
[[2]]
.... Dij= 2

i,j= 01, Bij= 
[[-2]]
.... Dij= -2
.... Dij= 0

i,j= 02, Bij= 
[[ 2  2]
 [-2  4]]

i,j= 00, Bij= 
[[4]]
.... Dij= 4

i,j= 01, Bij= 
[[-2]]
.... Dij= -2
.... Dij= 12
.... Dij= -36

i,j= 02, Bij= 
[[-5  2  2]
 [ 2  3 -2]
 [-2 -2  2]]

i,j= 00, Bij= 
[[ 3 -2]
 [-2  2]]

i,j= 00, Bi